apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-python
  namespace: demo

spec:
  replicas: 1

  selector:
    matchLabels:
      app: demo-python

  template:
    metadata:
      labels:
        app: demo-python

    spec:

      containers:

      - name: demo

        image: ghcr.io/fenixonline/argocd-demo:de78eab24b8fcc295cf2530565142e0669d13b3b

        imagePullPolicy: Always

        ports:

        - containerPort: 5000