apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-python
  namespace: demo

spec:
  replicas: 2

  selector:
    matchLabels:
      app: demo-python

  template:
    metadata:
      labels:
        app: demo-python

    spec:

      containers:

      - name: demo

        image: ghcr.io/fenixonline/argocd-demo:7202a4230b1d5bdf4506d936ca843cb1e4573843

        imagePullPolicy: Always

        ports:

        - containerPort: 5000