apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-python
  namespace: demo

spec:
  replicas: 1

  selector:
    matchLabels:
      app: demo-python

  template:
    metadata:
      labels:
        app: demo-python

    spec:

      containers:

      - name: demo

        image: ghcr.io/fenixonline/argocd-demo:a23f25e5973977adc3b8e6c1a19a3e021180f97d

        imagePullPolicy: Always

        ports:

        - containerPort: 5000